### ISSUE TITLE
birthdate

### ISSUE THREAD

**Issue by Flo-Schield-Bobby** [simde-utc/ginger#40]
Hello,

Petite question par rapport au modèle ;

L'attribut "legalAge" des utilisateurs indique un booléen en fonction du fait que l'utilisateur soit adulte ou non.

    // ginger/class/GingerAccountsApi.class.php
    class GingerAccountsApi implements AccountsInterface {
        // [...]
        protected function parseResponse($response) {
            if ($response === null) {
                throw new AccountsApiException("Null returned");
            }
            $account = new Account();
            // [...]
            $account->legalAge = $response->is_adulte;
            return $account;
        }
    }

Est-ce que c'est volontaire pour masquer la date de naissance, considérée comme confidentiel ?

En fait, pour la billetterie associative, je cherche un moyen de savoir si l'utilisateur sera majeur ou non -- le jour de l'évènement --, et non le jour où il s'inscrit.

Pour le moment, le seul moyen que j'ai est de rechecker (nouvel appel Ginger) le jour où il entre à l'évènement s'il est bien majeur ou non ;

Mais ce serait plus pratique de savoir le jour où il s'inscrit s'il sera majeur ou non le jour de l'évènement en question...

Si masquer la date de naissance est bien volontaire,
Est-ce qu'on pourrait imaginer une solution qui consisterait à envoyer une date (celle de l'évènement), et que l'API dise si oui ou non l'utilisateur sera majeur à ce moment là ?

**Comment by apuyou** [comment]
Hello,

Ginger n'a pas l'info car l'UTC a souhaité transmettre uniquement un booléen, afin de limiter les données personnelles manipulées dans les systèmes des assos.

Le comportement adopté par les clients actuellement est de revérifier régulièrement pour les utilisateurs qui ne sont pas majeurs. Cela est acceptable car la majorité des utilisateurs sont majeurs et, une fois majeur, tu ne redeviens pas mineur.

Dans ton schéma, ça donnerait ça : 
* tu stockes le booléen au moment de l'inscription
* le jour de l'événement, tu appelles ginger à nouveau *uniquement pour les mineurs* pour mettre à jour la valeur

**Comment by Flo-Schield-Bobby** [comment]
Hello Arthur,


Merci pour ta réponse rapide ;
Ouaip je me doutais que l'info devait être masquée, je comprend le point de vue de l'UTC sur la question.

C'est bien le schéma de secours que j'ai mis en place pour le moment.

Merci à toi :)
