### ISSUE TITLE
Erreur lors de la récupération des infos d'un badge

### ISSUE THREAD

**Issue by trecouvr** [simde-utc/ginger#41]
Lors de la récupération des infos de certain badges on obtient une erreur du type :

``` json
{"error":{"code":500,"message":"Unable to execute INSERT statement [INSERT INTO `personne` (`ID`, `LOGIN`, `PRENOM`, `NOM`, `MAIL`, `TYPE`, `IS_ADULTE`, `BADGE_UID`, `EXPIRATION_BADGE`, `CREATED_AT`, `UPDATED_AT`) VALUES (:p0, :p1, :p2, :p3, :p4, :p5, :p6, :p7, :p8, :p9, :p10)] [wrapped: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry \'AAAABBBB\' for key \'personne_U_2\']"}}
```

(HTTP code 500)

**Comment by pauljenny** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Double-diplômes des ESCOMiens dans Ginger](https://trello.com/c/Sd94nDmH/11-double-dipl%C3%B4mes-des-escomiens-dans-ginger)

**Comment by NastuzziSamy** [comment]
Bug connu appelé "Bug des ESCOMs".

Ca se produit uniquement lorsqu'un.e escommien.ne rejoint l'UTC avec un login différent mais avec la même carte, d'où l'erreur sur le champ unique du badge.

Résolu dans la v2 de Ginger
